### ISSUE TITLE
HTML parsing error

### ISSUE THREAD

**Issue by leecheeyong** [zyrouge/node-genius-lyrics#41]
I got this error when I tried to use this module without the API key, which scrapes the genius lyrics.

```
undefined:1
<!DOCTYPE html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at SongsClient.<anonymous> (/home/runner/terminal/node_modules/genius-lyrics/dist/songs/client.js:47:37)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/terminal/node_modules/genius-lyrics/dist/songs/client.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)```

**Comment by zyrouge** [comment]
Code?

**Comment by leecheeyong** [comment]
```const Genius = require("genius-lyrics");
const Client = new Genius.Client();
(async () => {
const searches = await Client.songs.search("faded");


const firstSong = searches[0];
console.log("About the Song:\n", firstSong, "\n");
console.log(firstSong)
})();```

**Comment by leecheeyong** [comment]
I ran an axios fetch request to the genius lyrics page and the page begins with:
```
<!doctype html>
<html>
  <head>
    <title>Alan Walker – Faded Lyrics | Genius Lyrics</title>
```

**Comment by zyrouge** [comment]
> I ran an axios fetch request to the genius lyrics page and the page begins with:
> 
> ```
> <!doctype html>
> <html>
>   <head>
>     <title>Alan Walker – Faded Lyrics | Genius Lyrics</title>
> ```

That's weird since the results are different. The error is probably due to cloudflare check, but your request from axios didn't trigger that check. Currently, there is no way of bypassing cloudflare check but I'll see what I can do. I keep this open until then.

**Comment by leecheeyong** [comment]
> > I ran an axios fetch request to the genius lyrics page and the page begins with:
> > ```
> > <!doctype html>
> > <html>
> >   <head>
> >     <title>Alan Walker – Faded Lyrics | Genius Lyrics</title>
> > ```
> 
> That's weird since the results are different. The error is probably due to cloudflare check, but your request from axios didn't trigger that check. Currently, there is no way of bypassing cloudflare check but I'll see what I can do. I keep this open until then.

I do believe that it isn't, I've dealt with many cloudflare check and normally cloudflare checks would be:
Page begins with:
```
<!DOCTYPE html><html lang="en"><head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Genius</title>
```
and the body content would have 
```
 <div class="text alert">
        <h1>Scrrrr!!</h1>
        <div class="dek">Sorry, we have to make sure you're a human before we can show you this page.</div>
        <div class="cloudflare_content">
          <form id="challenge-form" class="challenge-form" action="/young-captain-na-li-dou-shi-ni-lyrics?__cf_chl_f_tk=osDcIXsJsHgwkalPyNRqy_UNjB9G_PMl3Ud7QnrFmwU-1672043083-0-gaNycGzNCBE" method="POST" enctype="application/x-www-form-urlencoded">
    <div id="cf-please-wait" style="display: none;">
```

A Screenshot of the page:

<img width="829" alt="image" src="https://user-images.githubusercontent.com/81070048/209525323-6f3a7d45-35e4-4ed1-9d4a-74b9c422f0ca.png">

**Comment by zyrouge** [comment]
> > > I ran an axios fetch request to the genius lyrics page and the page begins with:
> > > ```
> > > <!doctype html>
> > > <html>
> > >   <head>
> > >     <title>Alan Walker – Faded Lyrics | Genius Lyrics</title>
> > > ```
> > 
> > 
> > That's weird since the results are different. The error is probably due to cloudflare check, but your request from axios didn't trigger that check. Currently, there is no way of bypassing cloudflare check but I'll see what I can do. I keep this open until then.
> 
> I do believe that it isn't, I've dealt with many cloudflare check and normally cloudflare checks would be: Page begins with:
> 
> ```
> <!DOCTYPE html><html lang="en"><head>
>     <meta charset="UTF-8">
>     <meta http-equiv="X-UA-Compatible" content="IE=edge">
>     <meta name="viewport" content="width=device-width, initial-scale=1.0">
>     <title>Genius</title>
> ```
> 
> and the body content would have
> 
> ```
>  <div class="text alert">
>         <h1>Scrrrr!!</h1>
>         <div class="dek">Sorry, we have to make sure you're a human before we can show you this page.</div>
>         <div class="cloudflare_content">
>           <form id="challenge-form" class="challenge-form" action="/young-captain-na-li-dou-shi-ni-lyrics?__cf_chl_f_tk=osDcIXsJsHgwkalPyNRqy_UNjB9G_PMl3Ud7QnrFmwU-1672043083-0-gaNycGzNCBE" method="POST" enctype="application/x-www-form-urlencoded">
>     <div id="cf-please-wait" style="display: none;">
> ```
> 
> A Screenshot of the page:
> 
> <img alt="image" width="829" src="https://user-images.githubusercontent.com/81070048/209525323-6f3a7d45-35e4-4ed1-9d4a-74b9c422f0ca.png">

This could maybe be fixed with proper headers. I'll have to analyse it though. Meanwhile you could check the headers send from this library and the request done with axios and check the differences.

**Comment by leecheeyong** [comment]
It is kind of weird though, axios shouldn't work if the cloudflare anti scrape feature was turned on, this confuses me alot

**Comment by leecheeyong** [comment]
> It is kind of weird though, axios shouldn't work if the cloudflare anti scrape feature was turned on, this confuses me alot

It doesn't seems like the headers matter:
```
  fetch({ url: "https://genius.com/young-captain-na-li-dou-shi-ni-lyrics" }).then(response => {
            var { data } = response;
            const $ = cheerio.load(data);

            const selectors = [
                () => $(".lyrics").text().trim(),
                () =>
                    $("div[class*='Lyrics__Container']")
                        .toArray()
                        .map((x) => {
                            const ele = $(x);
                            ele.find("br").replaceWith("\n");
                            return ele.text();
                        })
                        .join("\n")
                        .trim(),
            ];
            

        for (const x of selectors) {
            const lyrics = x();
            if (lyrics?.length) {
                return removeChorus ? removeChorus(lyrics) : lyrics;
            }
        }
        });
```

**Comment by leecheeyong** [comment]
> > It is kind of weird though, axios shouldn't work if the cloudflare anti scrape feature was turned on, this confuses me alot
> 
> It doesn't seems like the headers matter:
> 
> ```
>   fetch({ url: "https://genius.com/young-captain-na-li-dou-shi-ni-lyrics" }).then(response => {
>             var { data } = response;
>             const $ = cheerio.load(data);
> 
>             const selectors = [
>                 () => $(".lyrics").text().trim(),
>                 () =>
>                     $("div[class*='Lyrics__Container']")
>                         .toArray()
>                         .map((x) => {
>                             const ele = $(x);
>                             ele.find("br").replaceWith("\n");
>                             return ele.text();
>                         })
>                         .join("\n")
>                         .trim(),
>             ];
>             
> 
>         for (const x of selectors) {
>             const lyrics = x();
>             if (lyrics?.length) {
>                 return removeChorus ? removeChorus(lyrics) : lyrics;
>             }
>         }
>         });
> ```

With this code, there are no headers, which means default to the axios user agent

**Comment by AliAryanTech** [comment]
++
Same, tho
![Well](https://telegra.ph/file/4b3761639dbcca9ed1741.jpg)

**Comment by AliAryanTech** [comment]
found API to use it, it's working fine

**Comment by leecheeyong** [comment]
> found API to use it, it's working fine

What do you mean by that ?

**Comment by AliAryanTech** [comment]
> > found API to use it, it's working fine
> 
> What do you mean by that ?

just a delayed API which can scrap lines

**Comment by leecheeyong** [comment]
> > > found API to use it, it's working fine
> > 
> > 
> > What do you mean by that ?
> 
> just a delayed API which can scrap lyrics

could you mentioning about the api here, thanks

**Comment by pendragons-code** [comment]
As of 25-03-2023, the fix for the rate limit has not been implemented. It should be noted that the issue only persists when using a enterprise-like ip address. Whereas on things like a home network it would not affect you at all.
 I like this project and I really hope to see it succeed.

**Comment by Alphaegen** [comment]
This seems to crash our entire script when simply using the `search` function. We've put the code within a try/catch but that hasn't prevented the crash. Am I missing something?

You can check the `beta-(Bugs-are-expected)` branch in the `ZerioDev/Music-Bot` project for the specific code. Here's a link. https://github.com/ZerioDev/Music-bot/blob/beta-(Bugs-are-expected)/src/buttons/lyrics.js

**Comment by AliAryanTech** [comment]
I fixed this problem, now everything working.

**Comment by Bibyyy** [comment]
Hello, i have the same problem again when i host my bot on replit. How can i fix it ?

**Comment by FelixSimonB** [comment]
> > Hello, i have the same problem again when i host my bot on replit. How can i fix it ?
> 
> Use my API https://weeb-api.vercel.app/docs Check Misc session

Why not just share what you did?

**Comment by AliAryanTech** [comment]
> > > Hello, i have the same problem again when i host my bot on replit. How can i fix it ?
> > 
> > 
> > Use my API https://weeb-api.vercel.app/docs Check Misc session
> 
> Why not just share what you did?
Here: 
- https://weeb-api.vercel.app/genius?query=let%20me%20down%20slowly
- https://weeb-api.vercel.app/lyrics?url=https://genius.com/Alec-benjamin-let-me-down-slowly-lyrics

**Comment by FelixSimonB** [comment]
> > > > Hello, i have the same problem again when i host my bot on replit. How can i fix it ?
> > > 
> > > 
> > > Use my API https://weeb-api.vercel.app/docs Check Misc session
> > 
> > 
> > Why not just share what you did?
> > Here:
> 
> * https://weeb-api.vercel.app/genius?query=let%20me%20down%20slowly
> * https://weeb-api.vercel.app/lyrics?url=https://genius.com/Alec-benjamin-let-me-down-slowly-lyrics

It's your API not the fix. What I meant was how did you fix the captcha error? or did you used other package do it? 

Also tested your API and some lyrics format are kinda off https://weeb-api.vercel.app/lyrics?url=https://genius.com/Justin-bieber-never-say-never-lyrics but thanks for free public API 👍

**Comment by zyrouge** [comment]
There is no way to bypass captcha, unless you solve it. Using hosts that are not blacklisted would also be a way to avoid captcha, which is how proxy would work in this case. Maybe there is something I don't know that enables bypassing this, perhaps something like cookie.

**Comment by leecheeyong** [comment]
I think the conclusion to this issue would be the following:

1. Not using enterprise-liked IPs 
2. Solve the captcha once in awhile (when it occurs)
3. Use services like 2captcha to solve the captcha
4. Hop between IP addresses
5. Try other APIs

**Comment by Kisakay** [comment]
Maybe let the user pass proxy on the .search() function ?
With http-proxy-agent, etc ?

**Comment by mrepol742** [comment]
I'm able to bypass this captcha somehow by adding user-agents

```ts
  const client = new Genius.Client();
  const origGet = client.request.get.bind(client.request);

  client.request.get = async (url: string): Promise<string> => {
    const res = await request(url, {
      headers: {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
      },
    });
    return await res.body.text();
  };
  const searches = await client.songs.search(query);
```
